# Generated by Django 4.0.10 on 2025-03-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='times_minute',
            new_name='times_minutes',
        ),
    ]
