# Generated by Django 4.0.10 on 2025-03-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_times_minute_recipe_times_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='times_minutes',
            new_name='time_minutes',
        ),
    ]
